Repository patha454/dpatch, pull requests merged in 2020-11, with the labels that each got.

#14 Documentation: Correct doccomment for `generate_long_jump`.
  dpatch/x64_code_generator.c
Labels: documentation

#15 Feature: Dedicated `machine_code` module.
  dpatch/CMakeLists.txt
  dpatch/include/code_generator.h
  dpatch/include/machine_code.h
  dpatch/include/metamorphosis.h
  dpatch/include/status.h
  dpatch/machine_code.c
  dpatch/main.c
  dpatch/metamorphosis.c
  dpatch/x64_code_generator.c
Labels: enhancement

#16 Refactor: Strict C90 syntax.
  dpatch/include/status.h
Labels: refactor

#17 Feature: Report `dlopen` errors with `dlerror`.
  dpatch/main.c
Labels: enhancement

#18 Feature: Build as a link audit library.
  README.md
  demo/CMakeLists.txt
  dpatch/CMakeLists.txt
  dpatch/main.c
Labels: enhancement

#19 Feature: `patch` and `patch_set` API.
  dpatch/CMakeLists.txt
  dpatch/include/machine_code.h
  dpatch/include/patch.h
  dpatch/include/patch_set.h
  dpatch/include/status.h
  dpatch/machine_code.c
  dpatch/main.c
  dpatch/patch.c
  dpatch/patch_set.c
Labels: enhancement

#20 Feature: Script patching.
  dpatch/CMakeLists.txt
  dpatch/include/patch.h
  dpatch/include/patch_script.h
  dpatch/include/status.h
  dpatch/main.c
  dpatch/patch.c
  dpatch/patch_script.c
Labels: enhancement

#21 Refactor: Delete commented-out code.
  dpatch/main.c
Labels: refactor

#22 Feature: Error strings for status codes.
  dpatch/CMakeLists.txt
  dpatch/include/status.h
  dpatch/main.c
Labels: enhancement

#23 Feature: Take script from default or env var.
  dpatch/patch_script.c
Labels: enhancement

#24 Feature: Error handling macros.
  dpatch/include/status.h
  dpatch/machine_code.c
  dpatch/main.c
  dpatch/patch.c
  dpatch/patch_script.c
  dpatch/patch_set.c
  dpatch/x64_code_generator.c
Labels: enhancement

#26 Feature: Install self_patch script.
  demo/CMakeLists.txt
Labels: enhancement

#27 Documentation: Update to reflect new paths.
  README.md
Labels: documentation

#25 Refactor: Delete unused demos.
  demo/hello_world.c
  demo/print_load_address.c
Labels: refactor

#28 Bugfix: Add uncommited status file.
  dpatch/status.c
Labels: bug

#29 Bugfix: Delete missing installs.
  demo/CMakeLists.txt
Labels: bug

#30 Documenation: Correct heading in `README.md`.
  README.md
Labels: documentation

#31 Feature: Naieve dynamic patching
  demo/self_patch.c
  demo/self_patch.patch
  dpatch/main.c
Labels: enhancement
